# Generated by Django 5.1.6 on 2025-02-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thought',
            name='introspective_version',
            field=models.TextField(blank=True, null=True),
        ),
    ]
