# Generated by Django 5.1.6 on 2025-02-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts', '0002_thought_introspective_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='thought',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
